"""Initial migration

Revision ID: fd19d28f4349
Revises: 
Create Date: 2025-10-08 06:36:36.575361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd19d28f4349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etsy_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etsy_listing_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etsy_listing_id')
    )
    op.create_table('layout_hyperlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_type', sa.String(length=50), nullable=False),
    sa.Column('layout_name', sa.String(length=100), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout_type', sa.String(length=50), nullable=False),
    sa.Column('option_name', sa.String(length=100), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('svg_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('layout_type', sa.String(length=50), nullable=False),
    sa.Column('option_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('element_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('generated_planner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('ring', sa.String(length=50), nullable=True),
    sa.Column('tab', sa.String(length=50), nullable=True),
    sa.Column('weekly_layout', sa.String(length=50), nullable=True),
    sa.Column('daily_layout', sa.String(length=50), nullable=True),
    sa.Column('start_day', sa.String(length=20), nullable=True),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_planner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=False),
    sa.Column('ring', sa.String(length=50), nullable=True),
    sa.Column('tab', sa.String(length=50), nullable=False),
    sa.Column('weekly_layout', sa.String(length=50), nullable=False),
    sa.Column('daily_layout', sa.String(length=50), nullable=True),
    sa.Column('start_day', sa.String(length=20), nullable=False),
    sa.Column('pdf_filename', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_products',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.drop_table('monthly_layouts')
    op.drop_table('layout_metadata')
    op.drop_table('monthly_pages')
    with op.batch_alter_table('access_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('download_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('access_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.create_foreign_key(None, 'generated_planner', ['planner_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('download_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('access_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('planner_id')

    with op.batch_alter_table('access_code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('user_id')

    op.create_table('monthly_pages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('orientation', mysql.ENUM('portrait', 'landscape'), nullable=False),
    sa.Column('start_day', mysql.ENUM('monday', 'sunday'), nullable=False),
    sa.Column('month_number', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('image_filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('json_coordinates', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('monthly_pages_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('layout_metadata',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('layout_type', mysql.ENUM('weekly', 'daily'), nullable=False),
    sa.Column('option_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('total_pages', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('json_coordinates', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('json_links', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('uploaded_pdf', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('layout_metadata_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('monthly_layouts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('orientation', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('start_day', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('month_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_products')
    op.drop_table('saved_planner')
    op.drop_table('generated_planner')
    op.drop_table('user')
    op.drop_table('svg_element')
    op.drop_table('product_asset')
    op.drop_table('layout_template')
    op.drop_table('layout_hyperlink')
    op.drop_table('etsy_mapping')
    # ### end Alembic commands ###
